version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: always
    working_dir: /var/www
    environment:
      APP_ENV: production
      DB_HOST: database-1.cjs8m606i289.us-east-1.rds.amazonaws.com
      DB_DATABASE: database-1
      DB_USERNAME: nota
      DB_PASSWORD: Gtybn!gt%025Trza
    networks:
      - app_network
   
  web:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /var/www/.env:/var/www/.env 
    networks:
      - app_network

networks:
  app_network:

volumes:
  db_data:
