name: Deploy to AWS EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd app
            git fetch --all
            git reset --hard origin/main  # This ensures you get the latest version
            git pull origin main
            docker-compose -f docker-compose.prod.yml down
            docker-compose -f docker-compose.prod.yml up -d --build
      - name: Create .env file
        run: |
          echo "APP_ENV=production" > /var/www/.env
          echo "DB_CONNECTION=mysql" >> /var/www/.env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> /var/www/.env
          echo "DB_PORT=3306" >> /var/www/.env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> /var/www/.env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> /var/www/.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> /var/www/.env
          sudo mv /tmp/.env /var/www/.env  # Move to correct location
          sudo chmod 644 /var/www/.env  # Set correct permissions
