name: Deploy to AWS EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd app
            git fetch --all
            git reset --hard origin/main  # This ensures you get the latest version
            git pull origin main
            docker-compose -f docker-compose.prod.yml down
            docker-compose -f docker-compose.prod.yml up -d --build
      - name: Fix permissions for .env file
         run: sudo chmod -R 777 /var/www
      - name: Create .env file
        run: |
          echo "APP_ENV=production" | sudo tee /var/www/.env > /dev/null
          echo "DB_CONNECTION=mysql" | sudo tee -a /var/www/.env > /dev/null
          echo "DB_HOST=${{ secrets.DB_HOST }}" | sudo tee -a /var/www/.env > /dev/null
          echo "DB_PORT=3306" | sudo tee -a /var/www/.env > /dev/null
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" | sudo tee -a /var/www/.env > /dev/null
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" | sudo tee -a /var/www/.env > /dev/null
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" | sudo tee -a /var/www/.env > /dev/null