name: Deploy to AWS EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd app 
            git fetch --all
            git reset --hard origin/main            
            # Remove incorrect .env directory if it exists
            if [ -d "/var/www/.env" ]; then
              sudo rm -rf /var/www/.env
            fi
            touch /var/www/.env
            sudo chmod 644 /var/www/.env
            # Create the .env file
            cat <<EOF > /var/www/.env
            APP_ENV=production
            DB_CONNECTION=mysql
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=3306
            DB_DATABASE=database-1.cjs8m606i289.us-east-1.rds.amazonaws.com
            DB_USERNAME=nota
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            EOF

            # Ensure correct permissions
            chmod 644 /var/www/.env

            # Pull latest code
            git pull origin main

            # Restart the application
            docker-compose -f docker-compose.prod.yml down
            docker-compose -f docker-compose.prod.yml up -d --build

            # Clear and cache Laravel config
            docker exec laravel_app php artisan key:generate
            docker exec laravel_app php artisan config:clear
            docker exec laravel_app php artisan config:cache
      - name: Fix permissions for .env file
        run: sudo chmod -R 777 /var/www
      - name: Create .env file
        run: |
          echo "APP_ENV=production" | sudo tee /var/www/.env > /dev/null
          echo "DB_CONNECTION=mysql" | sudo tee -a /var/www/.env > /dev/null
          echo "DB_HOST=${{ secrets.DB_HOST }}" | sudo tee -a /var/www/.env > /dev/null
          echo "DB_PORT=3306" | sudo tee -a /var/www/.env > /dev/null
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" | sudo tee -a /var/www/.env > /dev/null
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" | sudo tee -a /var/www/.env > /dev/null
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" | sudo tee -a /var/www/.env > /dev/null